# Конфигурация для BWTelegramNotify
telegram:
  bot_username: "YOUR_BOT_USERNAME"
  bot_token: "YOUR_BOT_TOKEN"
  chat_ids:
    - "YOUR_CHAT_ID_1"
    - "YOUR_CHAT_ID_2"

notifications:
  velocity:
    join: "Игрок {player} присоединился к серверу."
    quit: "Игрок {player} покинул сервер."
    switch: "Игрок {player} сменил сервер с {from_server} на {to_server}."
  
  paper:
    join: "Игрок {player} присоединился к серверу."
    quit: "Игрок {player} покинул сервер."
    low_tps: "Внимание! Низкий TPS на сервере."
