telegram:
  bot_token: YOUR_BOT_TOKEN
  chat_ids:
    - "your_chat_id_1"
    - "your_chat_id_2"
  low_tps_threshold: 15.0
  tps_check_interval: 10

server:
  startup_message: "[PROJECTBW.RU] BWTelegramNotify Активен"
  player_join_message: "Игрок {player} зашел на сервер."
  player_quit_message: "Игрок {player} покинул сервер."
  server_change_message: "Игрок {player} сменил сервер на {server}."
  server_status_message:
    on: "Сервер включен."
    off: "Сервер выключен."