telegram:
  token: "YOUR_BOT_TOKEN"
  chats:
    - "CHAT_ID_1"
    - "CHAT_ID_2"

notifications:
  server_status: true
  player_login: true
  player_logout: true
  low_tps: true
  server_change: true
