name: BWTelegramNotify
version: 1.0-SNAPSHOT
main: me.projectbw.BWTelegramNotifyPaper # или me.projectbw.BWTelegramNotifyVelocity в зависимости от платформы
api-version: 1.21.4

commands:
  status:
    description: Проверка состояния бота
    permission: bwtelegram.notify.status
    permission-message: Вы не имеете прав для использования этой команды.