name: BWTelegramNotify
main: me.projectbw.BWTelegramNotifyPaper
version: 1.0-SNAPSHOT
author: ProjectBW
description: Плагин для отправки уведомлений в Telegram при событиях на сервере
api-version: 1.20
softdepend: [Vault]

commands:
  status:
    description: Показывает статус подключения бота к Telegram
    usage: /status
    permission: bwtelegramnotify.status

permissions:
  bwtelegramnotify.status:
    description: Позволяет использовать команду /status
    default: true
