name: BWTelegramNotify
version: 1.0
main: me.projectbw.BWTelegramNotifyPaper
api-version: 1.19
commands:
  status:
    description: Check the status of the Telegram bot
    usage: /status
permissions:
  bwtelegramnotify.status:
    description: Allows access to the /status command
    default: op