name: Maven Build & Auto Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build project using parent pom.xml
        run: mvn -B package --file pom.xml

      - name: Check built files
        run: |
          ls -R

      - name: Upload Paper JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: BWTelegramNotify-Paper
          path: Paper/target/BWTelegramNotify-Paper-*.jar
          retention-days: 7

      - name: Upload Velocity JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: BWTelegramNotify-Velocity
          path: Velocity/target/BWTelegramNotify-Velocity-*.jar
          retention-days: 7

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Paper JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: BWTelegramNotify-Paper
          path: Paper/target/

      - name: Download Velocity JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: BWTelegramNotify-Velocity
          path: Velocity/target/

      - name: Check downloaded files
        run: |
          ls -R Paper/target/
          ls -R Velocity/target/

      - name: Generate release tag
        id: set_tag
        run: |
          echo "TAG_NAME=$(date +'%d.%m.%Y') (Run #${{ github.run_number }})" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: "Auto Release ${{ env.TAG_NAME }}"
          body: "Автоматический релиз при обновлении main"
          files: |
            Paper/target/BWTelegramNotify-Paper-*.jar
            Velocity/target/BWTelegramNotify-Velocity-*.jar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}