messages:
  server_started: "✅ **Сервер {server} запущен!**"
  server_stopped: "⛔ **Сервер {server} выключен!**"
  player_join: "🔵 **Игрок {player} зашел на сервер {server}**"
  player_quit: "⚪ **Игрок {player} вышел с сервера {server}**"
  low_tps: "⚠ **Низкий TPS ({tps}) на сервере {server}!**"

settings:
  tps: 15.0
  update: true