# Конфигурация для Paper
telegram:
  token: "ВАШ_ТОКЕН"
  chatIds:
    - "ВАШ_ЧАТ_ID"  # Можно указать несколько чатов

messages:
  server_started: "✅ **Paper-сервер запущен!**"
  server_stopped: "⛔ **Paper-сервер выключен!**"
  player_join: "🔵 **Игрок зашел на сервер:** {player}"
  player_quit: "⚪ **Игрок вышел с сервера:** {player}"
  low_tps: "⚠ **Низкий TPS:** {tps}"

settings:
  tps_threshold: 15.0  # Порог для уведомлений о низком TPS