# Конфигурация для Paper
telegram:
  botToken: "ВАШ_ТОКЕН"
  chatIds:
    - "ВАШ_ЧАТ_ID"

messages:
  server_started: "✅ **Paper-сервер запущен!**"
  server_stopped: "⛔ **Paper-сервер выключен!**"
  player_join: "🔵 **Игрок зашел на сервер:** {player}"
  player_quit: "⚪ **Игрок вышел с сервера:** {player}"
  low_tps: "⚠ **Низкий TPS:** {tps}"

settings:
  tps: 15.0
  update: true