# Конфигурация для Paper
telegram:
  botToken: "ВАШ_ТОКЕН"
  chatId: "ВАШ_ЧАТ_ID"

notifications:
  serverStart: "Сервер Paper запущен!"
  serverStop: "Сервер Paper выключен!"
  playerJoin: "Игрок {player} вошел на сервер."
  playerLeave: "Игрок {player} вышел с сервера."
  lowTPS: "Внимание! Низкий TPS: {tps}"
  playerIP: "Игрок {player} подключился с IP: {ip}"
